### PR TITLE
Source type for amazon

### PR DESCRIPTION
**Pull request by Ladas**
Add default source type for amazon and also make source type NOT NULL

Depends on:
- [x] https://github.com/ManageIQ/topological_inventory-core/pull/92

### CODE REVIEW

**Comment by Ladas** [comment]
cc @agrare

**Comment by Ladas** [comment]
@agrare should I do data migration for this? (creating the aws source type and filling it everywhere where we have a nil?) Or we'll just do it manually when the migration fails?

**Comment by agrare** [comment]
> should I do data migration for this? (creating the aws source type and filling it everywhere where we have a nil?) Or we'll just do it manually when the migration fails?

I think we should just let it fail since there's no way to know if it was supposed to be AWS or not and both our live deployments have source_type_id present for all sources.

**Comment by agrare** [comment]
@Ladas why does this depend on https://github.com/ManageIQ/topological_inventory-core/pull/92 ?  It doesn't look like it should

**Comment by Ladas** [comment]
@agrare well it all depends on changed schema, when putting it as dependencies I don't need to resolve conflicts for the schema :-)

**Pull request merged**
